knitpro/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    ProjectListView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    YarnCreateView,
    YarnListView,
    YarnUpdateView,
    RegisterView,
)

urlpatterns = [
    path('', ProjectListView.as_view()),
    path('project/new', ProjectCreateView.as_view()),
    path('project/<int:pk>', ProjectUpdateView.as_view()),
    path('project/<int:pk>/delete', ProjectDeleteView.as_view()),
    path('yarn/new', YarnCreateView.as_view()),
    path('yarn/', YarnListView.as_view()),
    path('yarn/<int:pk>', YarnUpdateView.as_view()),
    
    path('registration', RegisterView.as_view()),
	path('login', LoginView.as_view(next_page="/")),
	path('accounts/login/', LoginView.as_view(next_page="/")),
	path('logout', LogoutView.as_view(next_page="/")),
]

knitting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('knitpro.urls')),
]

knitpro/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.CharField(max_length=255)
    project_type = models.CharField(max_length=150)
    instructions = models.TextField(null = True, blank = True)
    start_time = models.DateTimeField(auto_now_add = True)
    end_time = models.DateTimeField( null = True, blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name
    
class Yarn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255,blank=True)
    brand = models.CharField(max_length=155, blank=True)
    weight = models.CharField(max_length=20, blank=True) 
    length = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null = True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null= True, blank=True)

    def __str__(self):
        return f"{self.name}, {self.brand}"

knitpro/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from .models import Project, Yarn

class ProjectListView(LoginRequiredMixin,ListView):
    model = Project
    context_object_name = 'projects'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['name', 'project_type', 'instructions']
    success_url = "/yarn/new"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
class ProjectUpdateView(UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['name', 'project_type', 'instructions', 'end_time']
    success_url = "/"

    def test_func(self):
        project = self.get_object()
        return self.request.user == project.user

class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    model = Project
    success_url = "/"

    def test_func(self):
        project = self.get_object()
        return self.request.user == project.user


class YarnCreateView(LoginRequiredMixin, CreateView):
    model = Yarn
    fields = ['name', 'brand', 'length']
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existing_yarns'] = Yarn.objects.filter(user=self.request.user).exclude(name='')
        context['existing_projects'] = Project.objects.filter(user=self.request.user)
        return context

    def form_valid(self, form):
        existing_yarn_pk = self.request.POST.get('existing_yarn')

        if existing_yarn_pk:
            existing_yarn = get_object_or_404(Yarn, pk=existing_yarn_pk)
            project_pk = self.request.POST.get('project')

            if project_pk:
                existing_yarn.project_id = project_pk
            else:
                existing_yarn.project = None

            form.instance = existing_yarn
            return super().form_valid(form)
        form.instance.user = self.request.user
        return super().form_valid(form)
        
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class YarnUpdateView(UserPassesTestMixin, UpdateView):
    model = Yarn
    fields = ['name', 'brand', 'length']
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existing_yarns'] = Yarn.objects.filter(user=self.request.user).exclude(name='')
        context['existing_projects'] = Project.objects.filter(user=self.request.user)
        return context

    def form_valid(self, form):
        existing_yarn_pk = self.request.POST.get('existing_yarn')

        if existing_yarn_pk:
            existing_yarn = get_object_or_404(Yarn, pk=existing_yarn_pk)
            project_pk = self.request.POST.get('project')

            if project_pk:
                existing_yarn.project_id = project_pk
            else:
                existing_yarn.project = None

            form.instance = existing_yarn
            return super().form_valid(form)
        form.instance.user = self.request.user
        return super().form_valid(form)
        
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
    def test_func(self):
        yarn = self.get_object()
        return self.request.user == yarn.user
        
class YarnListView(LoginRequiredMixin, ListView):
    model = Yarn
    context_object_name = 'yarns'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

class YarnDeleteView(UserPassesTestMixin, DeleteView):
    model = Yarn
    success_url = "/"

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class RegisterView( CreateView):
	form_class = UserCreationForm
	template_name = "registration/registration.html"
	success_url = "/login"
	success_message = "Registration accepted. You can now log in. "

knitpro/templates/knitpro/about.html
{% extends "knitpro/base.html" %}

{% block "content" %}
	<p>See your knitting projects</p>
{% endblock "content" %}

knitpro/templates/knitpro/base.html
<!doctype html>
<!doctype html>
<html lang="en">
<head>
    <title>Knitting Projects</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        header {
            background-color: #F8F8F8;
            padding: 20px;
            text-align: center;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        
        h2 {
            color: #333;
            font-family: "Helvetica Neue", Arial, sans-serif;
        }
        
        .header-links {
            list-style-type: none;
            padding: 0;
            margin: 20px 0;
        }
        
        .header-links li {
            display: inline-block;
            margin-right: 10px;
        }
        
        .header-links li a {
            color: #555;
            text-decoration: none;
            font-weight: bold;
            padding: 8px 12px;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }
        
        .header-links li a:hover {
            background-color: #EEE;
        }
        
        body {
            font-family: "Helvetica Neue", Arial, sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.5;
        }
        
        .content {
            max-width: 800px;
            margin: 20px auto;
            padding: 0 20px;
        }
    </style>
</head>
<body>
    {% if user.is_authenticated %}
    <header>
        <h2>Cozy Knits</h2>
        <ul class="header-links">
            <li><a href="/">Projects</a></li>
            <li><a href="/yarn">Yarns</a></li>
            <li><a href="/logout">Logout</a></li>
            {{ user.name }}
        </ul>
    </header>
    {% endif %}
    
    <div class="content">
        {% block "content" %}
        <h1>Things</h1>
        {% endblock %}
    </div>
</body>
</html>

knitpro/templates/knitpro/project_confirm_delete.html
{% extends "knitpro/base.html" %}

{% block "content" %}
        <p>Permanently delete "<b>{{ object }}</b>". This operation cannot be undone.</p>

        <form method=post>
                {% csrf_token %}
                <input type=submit value="Delete">
        </form>
        <p><a href="/">Cancel</a></p>
{% endblock "content" %}

knitpro/templates/knitpro/project_form.html
{% extends "knitpro/base.html" %}

{% block "content" %}
    <style>
        form {
            margin-bottom: 20px;
        }
        
        input[type="submit"] {
            background-color: #96AE96;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
        }
        
        input[type="submit"]:hover {
            background-color: #999;
        }
        
        p {
            margin: 10px 0;
        }
        
        a {
            color: #555;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
        }
        
        a:hover {
            color: #999;
        }

        .delete:hover {
        	color:red;
        }
    </style>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Next">
    </form>

    {% if object %}
    <p><a class="delete" href="/project/{{ object.pk }}/delete">Delete</a></p>
    {% endif %}
    <a href="/">Cancel</a>
{% endblock "content" %}

knitpro/templates/knitpro/project_list.html
{% extends "knitpro/base.html" %}

{% block "content" %}
    <style>
        h1,h5 {
            color: #555;
            font-family: "Helvetica Neue", Arial, sans-serif;
        }
        
        ul {
            list-style-type: none;
            padding: 0;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        a {
            color: #555;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
        }
        
        a:hover {
            color: #999;
        }
    </style>

    <h1>Projects</h1>
    <ul>
        {% for project in projects %}
        <li>
            <a href="/project/{{ project.pk }}">{{ project }}
            Started: {{ project.start_time }}</a>
            <ul>
           <h5> Yarns used in this project:</h5>
                {% for yarn in project.yarn_set.all %}
                <li>{{ yarn.name }}</li>
                {% endfor %}
            </ul>
        </li>
        {% empty %}
        <li>No projects yet.</li>
        {% endfor %}
    </ul>

    <a href="/project/new">Create a new project</a>
{% endblock "content" %}

knitpro/templates/knitpro/yarn_form.html
{% extends "knitpro/base.html" %}

{% block "content" %}
  <style>
      form {
          margin-bottom: 20px;
      }
      
      input[type="submit"] {
          background-color: #96AE96;
          color: #fff;
          border: none;
          padding: 10px 20px;
          font-size: 16px;
          border-radius: 4px;
          cursor: pointer;
      }
      
      input[type="submit"]:hover {
          background-color: #999;
      }
      
      p {
          margin: 10px 0;
      }
      
      a {
          color: #555;
          text-decoration: none;
          font-weight: bold;
          transition: color 0.3s ease;
      }
      
      a:hover {
          color: #999;
      }

      .delete:hover {
      	color:red;
      }
  </style>
  
  <h1>Create a new Yarn</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="id_existing_yarn">Or select existing yarn:</label>
    <select id="id_existing_yarn" name="existing_yarn">
      <option value=""></option>
      {% for yarn in existing_yarns %}
        <option value="{{ yarn.pk }}">{{ yarn.name }}</option>
      {% endfor %}
    </select>
    <label for="id_project">Or select existing project:</label>
    <select id="id_project" name="project">
      <option value=""></option>
      {% for project in existing_projects %}
        <option value="{{ project.pk }}">{{ project.name }}</option>
      {% endfor %}
    </select>
    <input type="submit" value="Save">
  </form>
  
    {% if yarn %}
    	<p><a class="delete" href="/yarn/{{ yarn.pk }}/delete">Delete</a></p>
    {% endif %}

  <a href="/">Cancel</a>
{% endblock "content" %}

knitpro/templates/knitpro/yarn_list.html
{% extends "knitpro/base.html" %}

{% block "content" %}
    <style>
        h1,h5 {
            color: #555;
            font-family: "Helvetica Neue", Arial, sans-serif;
        }
        
        ul {
            list-style-type: none;
            padding: 0;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        a {
            color: #555;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
        }
        
        a:hover {
            color: #999;
        }
	</style>
	
	<h1>Yarns</h1>
	<ul>
	  {% for yarn in yarns %}
	    <li>
	      <a href="/yarn/{{ yarn.pk }}">{{ yarn }}</a>
	    </li>
	  {% empty %}
	    <li>No projects yet.</li>
	  {% endfor %}
	</ul>

	{% if yarn %}
		

	{% endif %}

	

	<a href="/yarn/new">Create a new yarn</a>
	<a href="/">Go Back</a>
{% endblock "content" %}